/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRoteiroRouteImport } from './routes/_authenticated/roteiro'
import { Route as AuthenticatedResultadoRouteImport } from './routes/_authenticated/resultado'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGraficosRouteImport } from './routes/_authenticated/graficos'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedDestinosRouteImport } from './routes/_authenticated/destinos'
import { Route as AuthenticatedDestinoNomeRouteImport } from './routes/_authenticated/destino.$nome'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoteiroRoute = AuthenticatedRoteiroRouteImport.update({
  id: '/roteiro',
  path: '/roteiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultadoRoute = AuthenticatedResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGraficosRoute = AuthenticatedGraficosRouteImport.update({
  id: '/graficos',
  path: '/graficos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDestinosRoute = AuthenticatedDestinosRouteImport.update({
  id: '/destinos',
  path: '/destinos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDestinoNomeRoute =
  AuthenticatedDestinoNomeRouteImport.update({
    id: '/destino/$nome',
    path: '/destino/$nome',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/destinos': typeof AuthenticatedDestinosRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/graficos': typeof AuthenticatedGraficosRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/resultado': typeof AuthenticatedResultadoRoute
  '/roteiro': typeof AuthenticatedRoteiroRoute
  '/destino/$nome': typeof AuthenticatedDestinoNomeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/destinos': typeof AuthenticatedDestinosRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/graficos': typeof AuthenticatedGraficosRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/resultado': typeof AuthenticatedResultadoRoute
  '/roteiro': typeof AuthenticatedRoteiroRoute
  '/': typeof AuthenticatedIndexRoute
  '/destino/$nome': typeof AuthenticatedDestinoNomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/destinos': typeof AuthenticatedDestinosRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/graficos': typeof AuthenticatedGraficosRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/resultado': typeof AuthenticatedResultadoRoute
  '/_authenticated/roteiro': typeof AuthenticatedRoteiroRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/destino/$nome': typeof AuthenticatedDestinoNomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/destinos'
    | '/favoritos'
    | '/graficos'
    | '/home'
    | '/mapa'
    | '/perfil'
    | '/quiz'
    | '/resultado'
    | '/roteiro'
    | '/destino/$nome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/destinos'
    | '/favoritos'
    | '/graficos'
    | '/home'
    | '/mapa'
    | '/perfil'
    | '/quiz'
    | '/resultado'
    | '/roteiro'
    | '/'
    | '/destino/$nome'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/destinos'
    | '/_authenticated/favoritos'
    | '/_authenticated/graficos'
    | '/_authenticated/home'
    | '/_authenticated/mapa'
    | '/_authenticated/perfil'
    | '/_authenticated/quiz'
    | '/_authenticated/resultado'
    | '/_authenticated/roteiro'
    | '/_authenticated/'
    | '/_authenticated/destino/$nome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roteiro': {
      id: '/_authenticated/roteiro'
      path: '/roteiro'
      fullPath: '/roteiro'
      preLoaderRoute: typeof AuthenticatedRoteiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resultado': {
      id: '/_authenticated/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof AuthenticatedResultadoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/graficos': {
      id: '/_authenticated/graficos'
      path: '/graficos'
      fullPath: '/graficos'
      preLoaderRoute: typeof AuthenticatedGraficosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/destinos': {
      id: '/_authenticated/destinos'
      path: '/destinos'
      fullPath: '/destinos'
      preLoaderRoute: typeof AuthenticatedDestinosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/destino/$nome': {
      id: '/_authenticated/destino/$nome'
      path: '/destino/$nome'
      fullPath: '/destino/$nome'
      preLoaderRoute: typeof AuthenticatedDestinoNomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDestinosRoute: typeof AuthenticatedDestinosRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedGraficosRoute: typeof AuthenticatedGraficosRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedResultadoRoute: typeof AuthenticatedResultadoRoute
  AuthenticatedRoteiroRoute: typeof AuthenticatedRoteiroRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDestinoNomeRoute: typeof AuthenticatedDestinoNomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDestinosRoute: AuthenticatedDestinosRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedGraficosRoute: AuthenticatedGraficosRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedResultadoRoute: AuthenticatedResultadoRoute,
  AuthenticatedRoteiroRoute: AuthenticatedRoteiroRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDestinoNomeRoute: AuthenticatedDestinoNomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
