/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRoteiroRouteImport } from './routes/_authenticated/roteiro'
import { Route as AuthenticatedResultadoRouteImport } from './routes/_authenticated/resultado'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedLoginRouteImport } from './routes/_authenticated/login'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoteiroRoute = AuthenticatedRoteiroRouteImport.update({
  id: '/roteiro',
  path: '/roteiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultadoRoute = AuthenticatedResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoginRoute = AuthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/home': typeof AuthenticatedHomeRoute
  '/login': typeof AuthenticatedLoginRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/resultado': typeof AuthenticatedResultadoRoute
  '/roteiro': typeof AuthenticatedRoteiroRoute
}
export interface FileRoutesByTo {
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/home': typeof AuthenticatedHomeRoute
  '/login': typeof AuthenticatedLoginRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/resultado': typeof AuthenticatedResultadoRoute
  '/roteiro': typeof AuthenticatedRoteiroRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/login': typeof AuthenticatedLoginRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/resultado': typeof AuthenticatedResultadoRoute
  '/_authenticated/roteiro': typeof AuthenticatedRoteiroRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favoritos'
    | '/home'
    | '/login'
    | '/mapa'
    | '/perfil'
    | '/quiz'
    | '/resultado'
    | '/roteiro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/favoritos'
    | '/home'
    | '/login'
    | '/mapa'
    | '/perfil'
    | '/quiz'
    | '/resultado'
    | '/roteiro'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/favoritos'
    | '/_authenticated/home'
    | '/_authenticated/login'
    | '/_authenticated/mapa'
    | '/_authenticated/perfil'
    | '/_authenticated/quiz'
    | '/_authenticated/resultado'
    | '/_authenticated/roteiro'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roteiro': {
      id: '/_authenticated/roteiro'
      path: '/roteiro'
      fullPath: '/roteiro'
      preLoaderRoute: typeof AuthenticatedRoteiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resultado': {
      id: '/_authenticated/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof AuthenticatedResultadoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/login': {
      id: '/_authenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthenticatedLoginRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLoginRoute: typeof AuthenticatedLoginRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedResultadoRoute: typeof AuthenticatedResultadoRoute
  AuthenticatedRoteiroRoute: typeof AuthenticatedRoteiroRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLoginRoute: AuthenticatedLoginRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedResultadoRoute: AuthenticatedResultadoRoute,
  AuthenticatedRoteiroRoute: AuthenticatedRoteiroRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
